language: elixir
elixir:
  - 1.2.6
otp_release:
  - 18.2
  - 19.1
matrix:
  # We are only interested on the newest/oldest pair
  exclude:
    - elixir: 1.4.0-rc.1
      otp_release: 18.2
    - elixir: 1.3.2
      otp_release: 19.1
addons:
  postgresql: "9.4"
services:
  - mysql
sudo: false # to use faster container based build environment
env:
  global:
    - PGVERSION=9.6
  matrix:
    - MIX_ENV=test
    - MIX_ENV=pg PGVERSION=9.2
    - MIX_ENV=pg
    - MIX_ENV=mysql
install:
  - mix local.hex --force
  - mix deps.get
before_script:
  - echo "local all postgres trust" | sudo tee /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgres 127.0.0.1/32 trust" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgrex_md5_pw 127.0.0.1/32 md5" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgrex_cleartext_pw 127.0.0.1/32 password" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo service postgresql restart
script:
  - ECTO_POOL=poolboy mix test
  - ECTO_POOL=sbroker mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - eric.meadows.jonsson@gmail.com
